// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/reg.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Region               string   `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e3ccfdf76fd55c7, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Request) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Request) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type Response struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e3ccfdf76fd55c7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Response) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto.RegisterFile("api/proto/reg.proto", fileDescriptor_5e3ccfdf76fd55c7) }

var fileDescriptor_5e3ccfdf76fd55c7 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xcf, 0x4e, 0x86, 0x30,
	0x10, 0xc4, 0xfd, 0x24, 0xfc, 0x5b, 0x51, 0x93, 0xd5, 0x18, 0xc2, 0x49, 0xf1, 0xc2, 0x09, 0x12,
	0x79, 0x03, 0x1f, 0xa1, 0x7a, 0xf2, 0x62, 0x2a, 0x59, 0x6b, 0x43, 0x6c, 0xb1, 0x5b, 0xdf, 0xff,
	0x0b, 0x6d, 0xc3, 0x69, 0xfb, 0x9b, 0xdd, 0x74, 0x66, 0xe0, 0x4e, 0x6e, 0x7a, 0xda, 0x9c, 0xf5,
	0x76, 0x72, 0xa4, 0xc6, 0xf0, 0xc2, 0x3c, 0x8c, 0xfe, 0x0d, 0x4a, 0x41, 0x7f, 0xff, 0xc4, 0x1e,
	0xef, 0x21, 0x67, 0x2f, 0x3d, 0xb5, 0xa7, 0xc7, 0xd3, 0x50, 0x8b, 0x08, 0xd8, 0x41, 0x65, 0xf4,
	0xb2, 0x1a, 0xf9, 0x4b, 0xed, 0x65, 0x58, 0x1c, 0x8c, 0x0f, 0x50, 0x38, 0x52, 0xda, 0x9a, 0x36,
	0x0b, 0x9b, 0x44, 0xbd, 0x80, 0x4a, 0x10, 0x6f, 0xd6, 0x30, 0xe1, 0x13, 0x34, 0x72, 0x59, 0x88,
	0xf9, 0xd3, 0xdb, 0x95, 0x4c, 0xfa, 0xfc, 0x2a, 0x6a, 0xef, 0xbb, 0x84, 0xcf, 0x70, 0xed, 0xe8,
	0xdb, 0x11, 0xff, 0xa4, 0x9b, 0xe8, 0xd3, 0x24, 0x31, 0x1c, 0xbd, 0xcc, 0x7b, 0x50, 0xa5, 0xd9,
	0x3b, 0x1c, 0x20, 0x13, 0xa4, 0xf0, 0x26, 0x36, 0x19, 0x53, 0xfe, 0xee, 0xf6, 0xe0, 0x68, 0xdd,
	0x5f, 0xbc, 0xd6, 0x1f, 0xe5, 0x18, 0x9b, 0x7f, 0x15, 0x61, 0xcc, 0xe7, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7a, 0x93, 0xbf, 0x02, 0x0d, 0x01, 0x00, 0x00,
}
